version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pf
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


